/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStokTelurRouteImport } from './routes/_app/stok-telur'
import { Route as AppProduksiRouteImport } from './routes/_app/produksi'
import { Route as AppPopulasiRouteImport } from './routes/_app/populasi'
import { Route as AppPenjualanRouteImport } from './routes/_app/penjualan'
import { Route as AppPengaturanRouteImport } from './routes/_app/pengaturan'
import { Route as AppPelangganRouteImport } from './routes/_app/pelanggan'
import { Route as AppPakanRouteImport } from './routes/_app/pakan'
import { Route as AppLaporanRouteImport } from './routes/_app/laporan'
import { Route as AppKeuanganRouteImport } from './routes/_app/keuangan'
import { Route as AppKesehatanRouteImport } from './routes/_app/kesehatan'
import { Route as AppKandangRouteImport } from './routes/_app/kandang'
import { Route as AppJadwalRouteImport } from './routes/_app/jadwal'
import { Route as AppGudangRouteImport } from './routes/_app/gudang'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStokTelurRoute = AppStokTelurRouteImport.update({
  id: '/stok-telur',
  path: '/stok-telur',
  getParentRoute: () => AppRoute,
} as any)
const AppProduksiRoute = AppProduksiRouteImport.update({
  id: '/produksi',
  path: '/produksi',
  getParentRoute: () => AppRoute,
} as any)
const AppPopulasiRoute = AppPopulasiRouteImport.update({
  id: '/populasi',
  path: '/populasi',
  getParentRoute: () => AppRoute,
} as any)
const AppPenjualanRoute = AppPenjualanRouteImport.update({
  id: '/penjualan',
  path: '/penjualan',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPelangganRoute = AppPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AppRoute,
} as any)
const AppPakanRoute = AppPakanRouteImport.update({
  id: '/pakan',
  path: '/pakan',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AppKesehatanRoute = AppKesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => AppRoute,
} as any)
const AppKandangRoute = AppKandangRouteImport.update({
  id: '/kandang',
  path: '/kandang',
  getParentRoute: () => AppRoute,
} as any)
const AppJadwalRoute = AppJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AppRoute,
} as any)
const AppGudangRoute = AppGudangRouteImport.update({
  id: '/gudang',
  path: '/gudang',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/gudang': typeof AppGudangRoute
  '/jadwal': typeof AppJadwalRoute
  '/kandang': typeof AppKandangRoute
  '/kesehatan': typeof AppKesehatanRoute
  '/keuangan': typeof AppKeuanganRoute
  '/laporan': typeof AppLaporanRoute
  '/pakan': typeof AppPakanRoute
  '/pelanggan': typeof AppPelangganRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/penjualan': typeof AppPenjualanRoute
  '/populasi': typeof AppPopulasiRoute
  '/produksi': typeof AppProduksiRoute
  '/stok-telur': typeof AppStokTelurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/gudang': typeof AppGudangRoute
  '/jadwal': typeof AppJadwalRoute
  '/kandang': typeof AppKandangRoute
  '/kesehatan': typeof AppKesehatanRoute
  '/keuangan': typeof AppKeuanganRoute
  '/laporan': typeof AppLaporanRoute
  '/pakan': typeof AppPakanRoute
  '/pelanggan': typeof AppPelangganRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/penjualan': typeof AppPenjualanRoute
  '/populasi': typeof AppPopulasiRoute
  '/produksi': typeof AppProduksiRoute
  '/stok-telur': typeof AppStokTelurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gudang': typeof AppGudangRoute
  '/_app/jadwal': typeof AppJadwalRoute
  '/_app/kandang': typeof AppKandangRoute
  '/_app/kesehatan': typeof AppKesehatanRoute
  '/_app/keuangan': typeof AppKeuanganRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/pakan': typeof AppPakanRoute
  '/_app/pelanggan': typeof AppPelangganRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/penjualan': typeof AppPenjualanRoute
  '/_app/populasi': typeof AppPopulasiRoute
  '/_app/produksi': typeof AppProduksiRoute
  '/_app/stok-telur': typeof AppStokTelurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/gudang'
    | '/jadwal'
    | '/kandang'
    | '/kesehatan'
    | '/keuangan'
    | '/laporan'
    | '/pakan'
    | '/pelanggan'
    | '/pengaturan'
    | '/penjualan'
    | '/populasi'
    | '/produksi'
    | '/stok-telur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/gudang'
    | '/jadwal'
    | '/kandang'
    | '/kesehatan'
    | '/keuangan'
    | '/laporan'
    | '/pakan'
    | '/pelanggan'
    | '/pengaturan'
    | '/penjualan'
    | '/populasi'
    | '/produksi'
    | '/stok-telur'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/gudang'
    | '/_app/jadwal'
    | '/_app/kandang'
    | '/_app/kesehatan'
    | '/_app/keuangan'
    | '/_app/laporan'
    | '/_app/pakan'
    | '/_app/pelanggan'
    | '/_app/pengaturan'
    | '/_app/penjualan'
    | '/_app/populasi'
    | '/_app/produksi'
    | '/_app/stok-telur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stok-telur': {
      id: '/_app/stok-telur'
      path: '/stok-telur'
      fullPath: '/stok-telur'
      preLoaderRoute: typeof AppStokTelurRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produksi': {
      id: '/_app/produksi'
      path: '/produksi'
      fullPath: '/produksi'
      preLoaderRoute: typeof AppProduksiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/populasi': {
      id: '/_app/populasi'
      path: '/populasi'
      fullPath: '/populasi'
      preLoaderRoute: typeof AppPopulasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penjualan': {
      id: '/_app/penjualan'
      path: '/penjualan'
      fullPath: '/penjualan'
      preLoaderRoute: typeof AppPenjualanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pelanggan': {
      id: '/_app/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AppPelangganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pakan': {
      id: '/_app/pakan'
      path: '/pakan'
      fullPath: '/pakan'
      preLoaderRoute: typeof AppPakanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keuangan': {
      id: '/_app/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kesehatan': {
      id: '/_app/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof AppKesehatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kandang': {
      id: '/_app/kandang'
      path: '/kandang'
      fullPath: '/kandang'
      preLoaderRoute: typeof AppKandangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jadwal': {
      id: '/_app/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof AppJadwalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gudang': {
      id: '/_app/gudang'
      path: '/gudang'
      fullPath: '/gudang'
      preLoaderRoute: typeof AppGudangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGudangRoute: typeof AppGudangRoute
  AppJadwalRoute: typeof AppJadwalRoute
  AppKandangRoute: typeof AppKandangRoute
  AppKesehatanRoute: typeof AppKesehatanRoute
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPakanRoute: typeof AppPakanRoute
  AppPelangganRoute: typeof AppPelangganRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPenjualanRoute: typeof AppPenjualanRoute
  AppPopulasiRoute: typeof AppPopulasiRoute
  AppProduksiRoute: typeof AppProduksiRoute
  AppStokTelurRoute: typeof AppStokTelurRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGudangRoute: AppGudangRoute,
  AppJadwalRoute: AppJadwalRoute,
  AppKandangRoute: AppKandangRoute,
  AppKesehatanRoute: AppKesehatanRoute,
  AppKeuanganRoute: AppKeuanganRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPakanRoute: AppPakanRoute,
  AppPelangganRoute: AppPelangganRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPenjualanRoute: AppPenjualanRoute,
  AppPopulasiRoute: AppPopulasiRoute,
  AppProduksiRoute: AppProduksiRoute,
  AppStokTelurRoute: AppStokTelurRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
